### PR TITLE
Updated Dockerfile

### PR DESCRIPTION
**Pull request by ntwrkguru**
### What does this PR do?

Updated Dockerfile to:
- Use PyEZ 2.4.1 as the base image
- Install Ansible via PIP instead of apk
- Added `no-cache` for apk to reduce image size
- Removed junos-eznz from `requirements.txt` since we use PyEZ as the base image anyway
- Added `/usr/bin/jsnapy` as the `ENTRYPOINT` allowing easier use as an executable container
- Corrected the `VOLUME` declaration for `/scripts`

### What issues does this PR fix or reference?

The `VOLUME` declaration was broken

### New Behavior

Simplified use as an executable by added an `ENTRYPOINT`

### Tests written?

No

### CODE REVIEW

**Comment by ntwrkguru** [comment]
Please squash commits when merging...it's a little messy. :-/

**Comment by ntwrkguru** [comment]
Please review @vnitinv or @rahkumar651991

**Comment by vnitinv** [comment]
@ntwrkguru We will test and then do the needful.

**Comment by ntwrkguru** [comment]
@rahkumar651991 @vnitinv Ok to merge?

**Pull request merged**
