### PR TITLE
Update Dockerfile 

### PR DESCRIPTION
**Pull request by dgarros**

### CODE REVIEW

**Comment by dgarros** [comment]
Hi @ntwrkguru 
I took a closer look at the Dockerfile and I think it's not working as expected right now.

The code is pulled from Github instead of using the local code. it mean that if you are have a special branch it will always pulled the code from the master branch on Github.

Also, considering that we are installing Ansible and Ansible Galaxy modules for Junos, should we use the container `juniper/pyez-ansible` as a base container ? 

Let me know if you have time to update the file or if you would like me to give it a try

Thanks
Damien

**Comment by ntwrkguru** [comment]
@dgarros Not sure what you mean. In the email thread, the consensus was not to peg to a release (tag), so the way it's written will pull from master. This is easy to fix and we can pull any tag or branch. My opinion is to peg to a release. Am I missing something?

**Comment by dgarros** [comment]
Sorry if there was a misunderstanding

From my point of view a Dockerfile packaged with a github project should always build from local files, instead of pulling the file from Github.  
The benefit is that you will automatically get a container to test the code, even when you are working on a new feature or when you are creating a new branch.
Also it integrates very well with Docker Hub because docker will automatically build new Docker tags for each Github tag and branch.

With the current Dockerfile, JSNAPy is installed from the latest commit of the branch master on Github
```dockerfile
RUN pip install git+https://github.com/Juniper/jsnapy.git
```

Let me give it a try, maybe it will help to make my point
and if needed, let's talk on the phone later today
Damien

**Comment by valjeanchan** [comment]
I may not fully understand how the automated build works but assume it'll got clone the branch and docker build in the same directory. 

What if we change the pip install command to "RUN pip install ." ? This will ensure the image are tied to the files within the cloned git branch.

Regards
Tony Chan

**Comment by dgarros** [comment]
@ntwrkguru 
I updated the Dockerfile on the branch `docker` to build from local files instead of Github 
it's inline with what we did for pyez https://github.com/Juniper/py-junos-eznc/blob/master/Dockerfile

Please can you check and let me know if it make sense.

Once we have an agreement, i'll use the same file to create a container for v1.0.0 based on github tag and I'll upload it manually on Docker hub 
All other tags will be created automatically

```
git checkout tags/v1.0.0 -b tag-v1.0.0
"copy the dockerfile since it doesn't exist in this tag"
docker build -t juniper/jsnapy:v1.0.0 .
```

**Comment by dgarros** [comment]
@valjeanchan 
Sorry I missed your previous message

`pip install .` sounds like a good idea, probably better than `python setup.py install` that we are using today, I'll update the file.

**Comment by dgarros** [comment]
File updated

**Comment by ntwrkguru** [comment]
👍

**Pull request merged**
